name: terraform-validate
description: Validate a Terraform configuration directory
author: Daniel Flook

inputs:
  path:
    description: Path to the Terraform configuration
    required: false
    default: .
  workspace:
    description: Name of the workspace to use for the `terraform.workspace` value while validating.
    required: false
    default: default
  backend_config:
    description: List of backend configs to set, one per line
    required: false
    default: ""
  backend_config_file:
    description: Path to a backend config file
    required: false
    default: ""

runs:
  using: docker
  image: docker://ghcr.io/dflook/terraform-github-actions@sha256:4c0a6f98ddafa03699d7fb059010f6b5f88d5a8903d1d2e66660ec799de9efad
  entrypoint: /entrypoints/validate.sh

branding:
  icon: globe
  color: purple
