name: terraform-validate
description: Validate a Terraform configuration directory
author: Daniel Flook

inputs:
  path:
    description: Path to the Terraform configuration
    required: false
    default: .
  workspace:
    description: Name of the workspace to use for the `terraform.workspace` value while validating.
    required: false
    default: default
  backend_config:
    description: List of backend configs to set, one per line
    required: false
    default: ""
  backend_config_file:
    description: Path to a backend config file
    required: false
    default: ""

runs:
  using: docker
  image: docker://danielflook/terraform-github-actions@sha256:1a3791b763b6aae2d68e5f724e12415dbc9da7190f9fe164651461787d43fa65
  entrypoint: /entrypoints/validate.sh

branding:
  icon: globe
  color: purple
